# Generated by Django 3.2.19 on 2023-05-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_react_stu_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNum', models.CharField(max_length=5)),
                ('stuNum', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
