# Generated by Django 3.2.19 on 2023-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230519_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('className', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('classCount', models.IntegerField()),
            ],
        ),
    ]
